ID="id"
USER_ID="uid"
EMAIL_ID = "email"
PLAN_ID="plan_id"

CHATBOT_ID="chatbot_id"
CHATBOT_NAME="chatbot_name"
CHATBOT_STATUS="chatbot_status"

CHATBOT_LIST="chatbot_list"

CONTENT_ID="content_id"
CONTENT="content"
CONTENT_LIST="content_list"
SOURCE="source"
SOURCE_TYPE="source_type"
LAST_UPDATED="last_updated"
CREATED_ON="created_on"
CHAR_COUNT="char_count"
STATUS="status"
TRAINED="trained"
TRAINING="training"
UNTRAINED="untrained"

NEWLY_ADDED="newlyAdded"
REMOVING="removing"

URL='url'
TEXT="text"

REPLY="reply"
QUERY="query"

SUCCESS = "success"
RESULT = "result"
ERROR="error"

PRO_PLAN="pro"
ESSENTIALS_PLAN="essential"
BASIC_PLAN="basic"
FREE_PLAN="free"
SUBSCRIPTION="subscription"
SUBSCRIPTION_STATUS="subscription_status"
SUBSCRIPTION_CANCELED="canceled"
SUBSCRIPTION_PLAN="subscription_plan"
SUBSCRIPTION_ID="subscription_id"

MESSAGE_USED="message_used"
MESSAGE_LIMIT="message_limit"
MESSAGE_CREDITS="message_credits"

COMPLETE="complete"
CUSTOMER="customer"

CHATBOT_LIMIT="chatbot_limit"
INITIAL_MESSAGE="initial_message"
QUICK_PROMPTS="quick_prompts"
THEME="theme"
PROFILE_PICTURE="profile_picture"
USER_MSG_COLOR="user_msg_color"
DISPLAY_NAME="display_name"
CHAT_ICON="chat_icon"
CHAT_BUBBLE_COLOR="chat_bubble_color"
INTERFACE="interface"

BASE_PROMPT="base_prompt"
PROMPT="prompt"
MODEL="model"
MODEL_VERSION="model_version"
TEMPERATURE="temperature"
GPT_3_5_TURBO= "gpt-3.5-turbo"
GPT_4="gpt-4"

LIGHT="light"
DARK="dark"